# Generated by Django 5.1.15 on 2026-06-18 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_category_alter_post_date_publication_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_publication',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
