# Generated by Django 5.1.15 on 2026-06-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_alter_post_date_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='actif',
            field=models.BooleanField(default=False),
        ),
    ]
